#!/bin/sh -ex

DB_NAME=vanilla
DB_USER=vanilla
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/vanilla


# unpack
mkdir -p $WEBROOT
unzip $SRC/vanilla-core.zip -d $WEBROOT/
rm $SRC/vanilla-core.zip
mv $WEBROOT/package/* $WEBROOT
mv $WEBROOT/package/.htaccess.dist $WEBROOT/.htaccess
mv $WEBROOT/conf/config-defaults.php $WEBROOT/conf/config.php
rm -rf $WEBROOT/package
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/conf
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/uploads

# configure apache
a2dissite 000-default
a2ensite vanilla
a2enmod rewrite


# start services
service mysql start
service apache2 start


# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
URL="http://127.0.0.1/index.php?p=/dashboard/setup"
CURL="curl -c /tmp/cookie -b /tmp/cookie"
DATA="TransientKey=&hpt=&RewriteUrls=1&Database-dot-Host=localhost&Database-dot-Name=$DB_NAME&Database-dot-User=$DB_USER&Database-dot-Password=$DB_PASS&HtaccessAction=dist&Garden-dot-Title=Turnkey+Vanilla&Email=admin%40example.com&Name=$ADMIN_NAME&Password=$ADMIN_PASS&PasswordMatch=$ADMIN_PASS&Continue_%2526rarr%253B=Continue+%E2%86%92"

chown www-data:www-data /var/www/vanilla
$CURL $URL
$CURL -d $DATA $URL
rm -f /tmp/cookie
chown root:root /var/www/vanilla
chown root:root /var/www/vanilla/.htaccess

# configure email
sed -i "s|\$Configuration\['Garden'\]\['Email'\]\['SupportName'\] = 'TurnKey Vanilla';|\$Configuration\['Garden'\]\['Email'\]\['SupportName'\] = 'TurnKey Vanilla';\n\$Configuration\['Garden'\]\['Email'\]\['SupportAddress'\] = 'admin@example.com';\n\$Configuration\['Garden'\]\['Email'\]\['UseSmtp'\] = '1';\n\$Configuration\['Garden'\]\['Email'\]\['SmtpHost'\] = '127.0.0.1';\n\$Configuration\['Garden'\]\['Email'\]\['SmtpUser'\] = '';\n\$Configuration\['Garden'\]\['Email'\]\['SmtpPassword'\] = '';\n\$Configuration\['Garden'\]\['Email'\]\['SmtpPort'\] = '25';\n\$Configuration\['Garden'\]\['Email'\]\['SmtpSecurity'\] = '';\n|" $WEBROOT/conf/config.php

chmod 640 $WEBROOT/conf/config.php

# create welcome page
DATE="2012-01-01 11:11:11"
WELCOME_TITLE='Welcome to Turnkey Vanilla'
WELCOME='<p>Welcome to your new forum, lets get you started...</p><ol><li>Sign in as <b>admin</b> and visit the <a href=\"/dashboard/settings\">dashboard</a> to customize your forum.</li><li>When ready, delete this welcome discussion and start some new ones.</li><li>Check out the discussion left by the vanilla dev team!</li></ol><p>For more information, check out the <a href=\"https://www.turnkeylinux.org/vanilla\">release notes</a> and the <a href=\"http://vanillaforums.org/docs/\">online documentation</p>'

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO GDN_Discussion VALUES ('5', NULL, NULL, '1', '2', NULL, NULL, NULL, '$WELCOME_TITLE', '$WELCOME', 'Html', NULL, '0', NULL, '0', '0', '1', '0', '$DATE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);"


# stop services
service mysql stop
service apache2 stop

