#!/bin/bash -e
# regenerate vanilla secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/vanilla/conf/config.php

SALT=$(mcookie | cut --bytes 1-10)
sed -i "s|\['Salt'\].*|\['Salt'\] = '$SALT';|" $CONF

PASSWORD=$(mcookie)
sed -i "s|\['Password'\].*|\['Password'\] = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=vanilla --pass="$PASSWORD"

